name: deploy_docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Building
      run: npm run docs:build
    - name: Misc
      run: |
        cd docs/.vuepress/dist
        echo 'docs.chiefonboarding.com' > CNAME
    - name: Initiate and push new repo
      uses: actions/checkout@v1
      run: |
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:chiefonboarding/Documentation.git master:gh-pages