name: deploy_docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          npm install -D vuepress
          npm run docs:build
      - name: Initiate and push new repo
        run: |
          cd docs/.vuepress/dist
          echo 'docs.chiefonboarding.com' > CNAME
          git config --global user.name GDay
          git config --global user.email 1939656+GDay@users.noreply.github.com

          git init
          git add -A
          git commit -m 'deploy'
          git remote add origin git@github.com:chiefonboarding/Documentation.git
          git push origin master:gh-pages