name: deploy_docs
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          npm install retypeapp --global
          retype build
      - name: Brotli Compression
        id: brotli
        uses: charlesworth/compress-action@1.0.0
        with:
          target-directory: '.retype'
      - name: Uploading files with rclone 
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync .retype/ storage:/caddy/chief_docs/
